on: 
  push:
    branches: 
      - develop
  workflow_dispatch:

name: Development release
run-name: Dev build triggered by @${{ github.actor }}

env:
  environment: develop
  android_app_name: "android-develop-release-v0.0.${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Install app dependencies
        run: flutter pub get
      - name: Analyze app code
        run: flutter analyze
      - name: Flutter doctor
        run: flutter doctor
      - name: Android release build
        run: flutter build apk --release
      - uses: actions/upload-artifact@v2
        with:
          name: "${{ env.android_app_name }}"
          path: "build/app/outputs/apk/release/app-release.apk"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: "${{ env.android_app_name }}"
      - name: Upload Android release
        uses: ncipollo/release-action@v1
        with:
          tag: v0.0.${{ github.run_number }}
          artifacts: "${{ env.android_app_name }}"
          name: "${{ env.android_app_name }}"
          token: ${{ secrets.TOKEN }}