on: 
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  workflow_dispatch:


name: Tests

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    name: Tests app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@
      - name: Install app dependencies
        run: flutter pub get
      - name: Test app
        run: flutter test --coverage