on: 
  pull_request:
    branches:
      - develop
  workflow_dispatch:


name: Tests

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  analyze:
    name: analyze-app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - name: Install app dependencies
        run: flutter pub get
      - name: Analyze app
        run: flutter analyze
